version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
  - dependency-name: "@angular/language-service"
    versions:
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
  - dependency-name: karma
    versions:
    - 6.2.0
    - 6.3.0
    - 6.3.1
    - 6.3.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
  - dependency-name: "@fortawesome/free-regular-svg-icons"
    versions:
    - 5.15.3
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.3
  - dependency-name: npm-check-updates
    versions:
    - 11.2.2
    - 11.3.0
  - dependency-name: typescript
    versions:
    - 4.1.5
  - dependency-name: ini
    versions:
    - 1.3.8
  rebase-strategy: disabled
